name : Tests

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
        #  schedule:
        #    - cron: '0 18 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Locate
        run: |
          export config="tests/*.yml"
          chmod +x tests/test.sh
          echo $config
          bash tests/test.sh
