name: Tests

on:
  push:
  schedule:
    - cron: '0 21 * * 6'

jobs:
  build:
    name: "Start test file: ${{ matrix.compose_file }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compose_file: [postgres.yml]
        include:
          - compose_file: postgres.yml
            POSTGRES_VERSION: 9
          - compose_file: postgres.yml
            POSTGRES_VERSION: 10
          - compose_file: postgres.yml
            POSTGRES_VERSION: 11
          - compose_file: postgres.yml
            POSTGRES_VERSION: 12

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/compose-action@1.2.1
        with:
          compose-file: ${{ matrix.compose_file }}
          compose-version: '1.27.4'

      - name: Run tests
        run: |
          chmod +x tests/test.sh
          for version in 9 10 11 12; do
            export POSTGRES_VERSION=$version
            bash tests/test.sh
          done