name: Tests

on:
  push:
  schedule:
    - cron: '0 21 * * 6'

jobs:
  build:
    name: "Start test file: ${{ matrix.compose_file }}"
    runs-on: ubuntu-latest
    strategy:
      include:
        - compose_file: postgres.yml
          POSTGRES_VERSION: ${{ matrix.POSTGRES_VERSION }}
        - compose_file: mysql.yml
          MYSQL_VERSION: ${{ matrix.MYSQL_VERSION }}
        - compose_file: mariadb.yml
          MARIADB_VERSION: ${{ matrix.MARIADB_VERSION }}
        - compose_file: activemq.yml
          ACTIVEMQ_VERSION: ${{ matrix.ACTIVEMQ_VERSION }}
        - compose_file: rabbitmq.yml
          RABBITMQ_VERSION: ${{ matrix.RABBITMQ_VERSION }}
        - compose_file: redis.yml
          REDIS_VERSION: ${{ matrix.REDIS_VERSION }}
      matrix:
        compose_file: [postgres.yml, graphite.yml, mysql.yml, rabbitmq.yml, standalone.yml, certs-customized.yml, mariadb.yml, postgres-old.yml, rabbitmq-old.yml, redis.yml, mariadb.yml]
        POSTGRES_VERSION:
          - 9
          - 10
          - 11
          - 12
        MYSQL_VERSION:
          - 8
          - 5
        MARIADB_VERSION:
          - 10
        ACTIVEMQ_VERSION:
          - latest
        RABBITMQ_VERSION:
          - 3
        REDIS_VERSION:
          - 6
          - 5


    env:
      config: ${{ matrix.compose_file }}
      POSTGRES_VERSION: ${{ matrix.POSTGRES_VERSION }}


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Test file: ${{ matrix.compose_file }}"
        run: |
          cd tests
          chmod +x test.sh
          bash test.sh