name : Tests

on:
  #push:
  #  tags:
  #    - "v*"
  #pull_request:
  #  tags:
  #    - "v*"
  #schedule:
  #  - cron: '40 12 * * 2'


jobs:
  build:
    name: " Start test files:${{matrix.compose-files}} "
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compose-files: [postgres.yml, mariadb.yml, graphite.yml, mysql.yml, rabbitmq.yml, standalone.yml, certs-customized.yml, postgres-old.yml, rabbitmq-old.yml, redis.yml]
            
            #Comment strings
            #|
            #|
            #graphite.yml, mysql.yml, postgres.yml, rabbitmq.yml, standalone.yml, certs-customized.yml, 
            #mariadb.yml, postgres-old.yml, rabbitmq-old.yml, redis.yml, mariadb.yml, postgres.yml
      
    steps:       
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: "Test files ${{matrix.compose-files}}"
        run: |
          cd tests
          ls -la
          pwd
          export config=${{ matrix.compose-files }}
          chmod +x test.sh
          echo $config
          bash test.sh
