name: Tests

on:
  push:
  schedule:
    - cron: '0 21 * * 6'

jobs:
  build:
    name: "Start test files: ${{ matrix.compose_file.compose_files }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compose_file:
          - { compose_file: postgres.yml, POSTGRES_VERSION: 12 }
          - { compose_file: postgres.yml, POSTGRES_VERSION: 11 }
          - { compose_file: postgres.yml, POSTGRES_VERSION: 10 }
          - { compose_file: postgres.yml, POSTGRES_VERSION: 9 }
          - { compose_file: activemq.yml, ACTIVEMQ_VERSION: latest }
          - { compose_file: certs-customized.yml }
          - { compose_file: certs.yml }
          - { compose_file: graphite.yml }
          - { compose_file: mariadb.yml, MARIADB_VERSION: 10 }
          - { compose_file: mysql.yml, MYSQL_VERSION: 8 }
          - { compose_file: mysql.yml, MYSQL_VERSION: 5 }
          - { compose_file: postgres-old.yml }
          - { compose_file: rabbitmq-old.yml }
          - { compose_file: rabbitmq.yml, RABBITMQ_VERSION: 3 }
          - { compose_file: redis.yml, REDIS_VERSION: 6 }
          - { compose_file: redis.yml, REDIS_VERSION: 5 }
          - { compose_file: standalone.yml }

    env:
      config: ${{ matrix.compose_file.compose_file }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Test files"
        run: |
          cd tests
          chmod +x test.sh
          bash test.sh