name: Tests

on:
  push:
  schedule:
    - cron: '0 21 * * 6'

jobs:
  build:
    name: "Start test file: ${{ matrix.compose_file }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compose_file: [postgres.yml, mysql.yml]
        version: [5, 8, 9, 10, 11, 12]


# graphite.yml, mysql.yml, rabbitmq.yml, standalone.yml, certs-customized.yml, mariadb.yml, postgres-old.yml, rabbitmq-old.yml, redis.yml, mariadb.yml


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Test file: ${{ matrix.compose_file}}"
        run: |
          cd tests
          export config=${{ matrix.compose_file }}
          for MYSQL_VERSION in 5 8; do
            export MYSQL_VERSION=$MYSQL_VERSION
            for POSTGRES_VERSION in 9 10 11 12; do
              export POSTGRES_VERSION=$POSTGRES_VERSION
            done
          done
          chmod +x test.sh
          bash test.sh