name : Tests

on:
  push:
  schedule:
    - cron: '0 21 * * 6'


jobs:
  build:
    name: " Start test files:${{matrix.compose-files}} "
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compose-files:
            - compose_file:
                compose_files: postgres.yml
                POSTGRES_VERSION: 9
        include:
            - ${{matrix.compose_file}}

    env:
      POSTGRES_VERSION: ${{ matrix.POSTGRES_VERSION }}
      config: ${{ matrix.compose_file.compose_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Test files"
        run: |
          cd tests
          chmod +x test.sh
          bash test.sh