name: "Run Database List"

on:
  push:
  schedule:
    - cron: '0 21 * * 6'

jobs:
  build:
    name: "Start test file: ${{ matrix.compose_file }}:${{matrix.version}}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compose_file: [postgres.yml]
        version: ["", "version=9", "version=10", "version=11", "version=12"]
        include:
          - compose_file: mysql.yml
            version: "mysql_version=5"
          - compose_file: mysql.yml
            version: "mysql_version=8"

    # graphite.yml, mysql.yml, rabbitmq.yml, standalone.yml, certs-customized.yml, mariadb.yml, postgres-old.yml, rabbitmq-old.yml, redis.yml, mariadb.yml


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Test file: ${{ matrix.compose_file }}:${{matrix.version}}"
        run: |
          cd tests
          export config=${{ matrix.compose_file }}
          for version in "${{ matrix.version }}"; do
            export POSTGRES_VERSION=${version#*=}
          done
          for mysql_version in "${{ matrix.version }}"; do
            export MYSQL_VERSION=${version#*=}
          done
          chmod +x test.sh
          bash test.sh
