name: "Run Database List"

on:
  push:
  schedule:
    - cron: '0 21 * * 6'

jobs:
  build:
    name: "Start test file: ${{ matrix.compose_file }}:${{matrix.version}}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compose_file: [postgres.yml]
        version: ["", "version=9", "version=10", "version=11", "version=12"]
        include:
          - compose_file: mysql.yml
            version: "version=5"                      #mysql 5
          - compose_file: mysql.yml
            version: "version=8"                      # mysql 8
          - compose_file: mysql.yml
            version: ""                               # mysql 5.7
          - compose_file: mariadb.yml
            version: "version=10"                     # mariadb 10
          - compose_file: mariadb.yml
            version: ""                               # mariadb 10.5
          - compose_file: activemq.yml
            version: "latest"                         # latest version activemq
          - compose_file: activemq.yml
            version: ""                               # activemq 5.14.3
          - compose_file: rabbitmq.yml
            version: ""                               # rabbitmq latest
          - compose_file: rabbitmq.yml
            version: "version=3"                      # rabbitmq 3
          - compose_file: redis.yml
            version: "version=5"                      # redis 5
          - compose_file: redis.yml
            version: "version=6"                      # redis 6
          - compose_file: graphite.yml
            version: ""                               # graphite latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Test file: ${{ matrix.compose_file }}:${{matrix.version}}"
        run: |
          cd tests
          # Export .yml files in variable config
          export config=${{ matrix.compose_file }} 
          # Sending version number in variable POSTGRES_VERSION
          for version in "${{ matrix.version }}"; do
            export POSTGRES_VERSION=${version#*=}                           # Deleting all symbols before version number
          done
          # Sending version number in variable MYSQL_VERSION       
          for mysql_version in "${{ matrix.version }}"; do
            export MYSQL_VERSION=${mysql_version#*=}                        # Deleting all symbols before version number
          done
          # Sending version number in variable MARIADB_VERSION               
          for mariadb_version in "${{ matrix.version }}"; do
               export MARIADB_VERSION=${mariadb_version#*=}                 # Deleting all symbols before version number
          done
          # Sending version number in variable ACTIVEMQ_VERSION
          for activemq_version in "${{ matrix.version }}"; do
               export ACTIVEMQ_VERSION=${activemq_version#*=}               # Deleting all symbols before version number
          done
          # Sending version number in variable RABBITMQ_VERSION
          for rabbitmq_version in "${{ matrix.version }}"; do
               export RABBITMQ_VERSION=${rabbitmq_version#*=}               # Deleting all symbols before version number
          done
          # Sending version number in variable REDIS_VERSION
          for redis_version in "${{ matrix.version }}"; do
               export REDIS_VERSION=${redis_version#*=}                     # Deleting all symbols before version number
          done
          chmod +x test.sh
          bash test.sh
