name : Tests

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
        #  schedule:
        #    - cron: '0 18 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
      strategy:
        matrix:
          compose-files: [activemq.yml, certs.yml, graphite.yml, mysql.yml, postgres.yml, rabbitmq.yml, standalone.yml, certs-customized.yml, mariadb.yml, postgres-old.yml, rabbitmq-old.yml, redis.yml]
      steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Start Postgres
        run: |
          export config=${{ matrix.compose-files }}
          chmod +x tests/test.sh
          echo $config
