name : Tests

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Locate
        run: |
          pwd
          ls -la
          chmod +x tests/test.sh
          bash -c "./tests/test.sh"
