name : Tests

on:
  schedule:
   - cron: '0 18 * * 6'
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Locate
        run: |
          export config=tests/postgres.yml
          chmod +x tests/test.sh
          bash tests/test.sh
